export const HANDLE_SETTINGS_CONNECTING_DEVICE = 'app/Settings/HANDLE_SETTINGS_CONNECTING_DEVICE';
export const HANDLE_SETTINGS_SAVE = 'app/Settings/HANDLE_SETTINGS_SAVE';
export const LOAD_DEVICES = 'app/Settings/LOAD_DEVICES';
export const LOAD_DEVICES_SUCCESS = 'app/Settings/LOAD_DEVICES_SUCCESS';
export const LOAD_DEVICES_ERROR = 'app/Settings/LOAD_DEVICES_ERROR';

