export const HANDLE_SETTINGS_CONNECTION_IP = 'app/Settings/HANDLE_SETTINGS_CONNECTION_IP';
export const HANDLE_SETTINGS_CONNECTION_PORT = 'app/Settings/HANDLE_SETTINGS_CONNECTION_PORT';
export const HANDLE_SETTINGS_CONNECTION_PROTOCOL = 'app/Settings/HANDLE_SETTINGS_CONNECTION_PROTOCOL';
export const HANDLE_SETTINGS_CONNECTION_PATIENT_MONITOR = 'app/Settings/HANDLE_SETTINGS_CONNECTION_PATIENT_MONITOR';
export const HANDLE_SETTINGS_SAVE = 'app/Settings/HANDLE_SETTINGS_SAVE';
