export const LOAD_SIMULATION_WAVEFORM_SUCCESS = 'app/Admin/LOAD_SIMULATION_WAVEFORM_SUCCESS';
export const LOAD_SIMULATION_WAVEFORM_ERROR = 'app/Admin/LOAD_SIMULATION_WAVEFORM_ERROR';
export const LOAD_SIMULATION_WAVEFORM = 'app/Admin/LOAD_SIMULATION_WAVEFORM';

export const LOAD_SIMULATION_VITAL_SIGN_SUCCESS = 'app/Admin/LOAD_SIMULATION_VITAL_SIGN_SUCCESS';
export const LOAD_SIMULATION_VITAL_SIGN_ERROR = 'app/Admin/LOAD_SIMULATION_VITAL_SIGN_ERROR';
export const LOAD_SIMULATION_VITAL_SIGN = 'app/Admin/LOAD_SIMULATION_VITAL_SIGN';
