/*
 *
 * PatientMonitorMobile constants
 *
 */

export const CHANGE_WAVEFORM_LAYOUT = 'app/PatientMonitor/CHANGE_WAVEFORM_LAYOUT';
export const RESET_WAVEFORM_LAYOUT = 'app/PatientMonitor/RESET_WAVEFORM_LAYOUT';
export const ADD_WAVEFORM_ITEM = 'app/PatientMonitor/ADD_WAVEFORM_ITEM';
export const REMOVE_WAVEFORM_ITEM = 'app/PatientMonitor/REMOVE_WAVEFORM_ITEM';
export const CHANGE_VITAL_SIGN_LAYOUT = 'app/PatientMonitor/CHANGE_VITAL_SIGN_LAYOUT';
export const RESET_VITAL_SIGN_LAYOUT = 'app/PatientMonitor/RESET_VITAL_SIGN_LAYOUT';
export const ADD_VITAL_SIGN_ITEM = 'app/PatientMonitor/ADD_VITAL_SIGN_ITEM';
export const REMOVE_VITAL_SIGN_ITEM = 'app/PatientMonitor/REMOVE_VITAL_SIGN_ITEM';
export const HANDLE_WAVEFORM_DRAWER_TOGGLE = 'app/PatientMonitor/HANDLE_WAVEFORM_DRAWER_TOGGLE';
export const HANDLE_WAVEFORM_DRAWER_CLOSE = 'app/PatientMonitor/HANDLE_WAVEFORM_DRAWER_CLOSE';
export const HANDLE_WAVEFORM_CHANGE = 'app/PatientMonitor/HANDLE_WAVEFORM_CHANGE';
export const HANDLE_WAVEFORM_COLOR_CHANGE = 'app/PatientMonitor/HANDLE_WAVEFORM_COLOR_CHANGE';
export const HANDLE_WAVEFORM_LINEWIDTH_CHANGE = 'app/PatientMonitor/HANDLE_WAVEFORM_LINEWIDTH_CHANGE';
export const HANDLE_RIGHT_DRAWER_TOGGLE = 'app/PatientMonitor/HANDLE_RIGHT_DRAWER_TOGGLE';
export const HANDLE_RIGHT_DRAWER_CLOSE = 'app/PatientMonitor/HANDLE_RIGHT_DRAWER_CLOSE';
export const HANDLE_VITAL_SIGN_CHANGE = 'app/PatientMonitor/HANDLE_VITAL_SIGN_CHANGE';
export const HANDLE_VITAL_SIGN_COLOR_CHANGE = 'app/PatientMonitor/HANDLE_VITAL_SIGN_COLOR_CHANGE';
export const HANDLE_POWER_BUTTON_TOGGLE = 'app/PatientMonitor/HANDLE_POWER_BUTTON_TOGGLE';
export const SOCKET_CONNECTED = 'app/PatientMonitor/SOCKET_CONNECTED';
export const HANDLE_WAVEFORM_TOOLBAR_GRID_ON_BUTTON_TOGGLE = 'app/PatientMonitor/HANDLE_WAVEFORM_TOOLBAR_GRID_ON_BUTTON_TOGGLE';
export const HANDLE_DISPLAY_MODE_CHANGE = 'app/PatientMonitor/HANDLE_DISPLAY_MODE_CHANGE';
export const HANDLE_VITAL_SIGN_FORMSTORAGE_CHANGE = 'app/PatientMonitor/HANDLE_VITAL_SIGN_FORMSTORAGE_CHANGE';
export const HANDLE_HEART_BEEP_SOUND_TOGGLE = 'app/PatientMonitor/HANDLE_HEART_BEEP_SOUND_TOGGLE';

